version: '3'
services:
  web:
    build: ./nginx
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - api
      - db
  api:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
      image: postgres
      restart: always
      environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
       PGDATA: "/var/lib/postgresql/data"
      ports:
      - "5432:5432"
      volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - mem-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 4240:4240
volumes:
 mem-db:
